
plugins {
    id 'groovy'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation libs.groovy.all

    implementation libs.guava
}

testing {
    suites {
        test {
            useSpock('2.4-groovy-4.0')
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {

    mainClass = 'Main'
}
